### ISSUE TITLE
Previous and Next articles must be of same category

### ISSUE THREAD

**Issue by mr-vaibh** [mr-vaibh/neutraltip#2]
On the standard article page,
At the bottom, the 'PREVIOUS' and 'NEXT' articles must be of the same category as the current page itself.

For eg:
in the page https://neutraltip.herokuapp.com/article/why-neutral-tip-rzzlvlm/
category of the previous and next article must be 'social'

HINT: as of now, the code to be changed is in article app > views.py > ArticleDetailView class

**Comment by aniruddh-pramod** [comment]
Hey could I take this up? I'm unsure of how I should be running this to see how my changes affect though

**Comment by aniruddh-pramod** [comment]
#5 Will this do the trick?
